<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 9/29/18
 * Time: 23:12
 */

namespace VatGia\Model;


use \Illuminate\Database\Eloquent\Model as LaravelModel;
use InvalidArgumentException;

class Model extends LaravelModel
{

    use CustomizableFieldsWithPrefixTrait;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->setConnection(config('database.default'));
    }


    public function setConnection($name)
    {
        $connection = config('database.connections.' . $name);
        if (!$connection) {
            throw new InvalidArgumentException("Database [$name] not configured.");
        }

        app()['last_connection'] = config('database.connections.' . $name);

        return parent::setConnection($name); // TODO: Change the autogenerated stub
    }

}