<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 9/29/18
 * Time: 23:12
 */

namespace VatGia\Model;


use \Illuminate\Database\Eloquent\Model as LaravelModel;
use Illuminate\Support\Facades\Config;

class Model extends LaravelModel
{

    /**
     * Create a new Eloquent model instance.
     *
     * @param  array $attributes
     * @return void
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->setConnection();
    }

    /**
     * Set the connection associated with the model.
     *
     * @param  string $name
     * @return $this
     */
    public function setConnection($name = null)
    {

        $database_config = Config::get('database');

        $name = $name ? $name : $database_config['default'];

        //Trường hợp chỉ định cụ thể connection
        $connection = Config::get('database.connections.' . $name);
        if (is_array($connection) && isset($connection['driver'])) {

            return parent::setConnection($name); // TODO: Change the autogenerated stub
        }

        //Trường hợp chỉ định 1 nhóm connections
        $connections = Config::get('database.connections.' . $name);
        if ($connections) {
            $connections = array_keys($connections);
            shuffle($connections);
            $name = $name . '.' . reset($connections);

            return parent::setConnection($name); // TODO: Change the autogenerated stub
        }

        return parent::setConnection($name); // TODO: Change the autogenerated stub
    }

}